Squashed commit of the following:
commit dba1e5c337678e7796ac891cb20923166a6764d3
Merge: 43e24790f 76139c6d2
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Thu Aug 20 20:07:40 2026 +0200

    Merge branch 'cmake-fix-compile' of https://github.com/MassimoPetracca/OpenSees into cmake-fix-compile

commit 43e24790f26660cae324f7a45fa52c44a3883419
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Thu Aug 20 19:58:18 2026 +0200

    TclElementCommands: split the element dispatch chain (MSVC C1061)

    A single if/else-if chain over every element name exceeds MSVC's 128-block
    nesting limit once enough elements are registered (fatal error C1061). Restart
    the dispatch as a second chain at LysmerTriangle: equivalent because every
    branch either sets theElement or returns, and names are unique across chains.

commit 76139c6d24f14346e73a54f2659ce7c0571bfbeb
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Thu Aug 20 19:58:18 2026 +0200

    TclElementCommands: split the element dispatch chain (MSVC C1061)

    A single if/else-if chain over every element name exceeds MSVC's 128-block
    nesting limit once enough elements are registered (fatal error C1061). Restart
    the dispatch as a second chain at LysmerTriangle: equivalent because every
    branch either sets theElement or returns, and names are unique across chains.

    Co-Authored-By: Claude Fable 5 <noreply@anthropic.com>

commit 6390b6966bc37319088a646a70d56b3588fb79ff
Merge: 318235bc3 2890cb36f
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Mon Aug 17 18:02:07 2026 +0200

    Merge branch 'master' into cmake-fix-compile

commit 318235bc3509266776e1f1074cb170f97225c5ef
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Wed Aug 5 15:26:00 2026 +0200

    mkl and superlu fixes

commit c0db5bf482e52449bd523b75f6b75b6f91c31189
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Tue Jul 28 19:00:54 2026 +0200

    remove eigen link

commit 70597967945399963e944db27d59c9ee4d8a5be3
Merge: a72e954c7 4843b74a9
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Tue Jul 28 17:01:23 2026 +0200

    Merge branch 'master' into cmake-fix-compile

commit a72e954c7ab341616c42eb3591cfbc1a909df7c5
Merge: 8da202567 098e28c48
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Thu Jul 23 10:03:05 2026 +0200

    Merge branch 'master' into cmake-fix-compile

commit 8da2025676c2f602a1051f63b7c7bc08f687885e
Merge: 7d1c9a216 d56e8d240
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Mon Jan 19 18:47:40 2026 +0100

    Merge branch 'master' into cmake-fix-compile

commit 7d1c9a216e9ce38ad939859f37bd5d74864e84c4
Merge: 8c21f0464 298e62bd3
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Fri Oct 3 17:56:46 2025 +0200

    Merge branch 'master' into cmake-fix-compile

commit 8c21f0464b4577d8330f7744b3f773ed213b7770
Merge: e1e3be690 e4a4bf8b2
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Mon Sep 29 09:51:17 2025 +0200

    Merge branch 'master' into cmake-fix-compile

commit e1e3be69056f6818523a0b62174a1c88674008cb
Merge: 20e63dbf1 bf7cfc849
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Wed Jul 23 10:58:40 2025 +0200

    Merge branch 'master' into cmake-fix-compile

commit 20e63dbf17c70147770fba15f20415f0baba50af
Merge: b20c6bcb7 66e7a4729
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Thu May 29 16:04:51 2025 +0200

    Merge branch 'master' into cmake-fix-compile

commit b20c6bcb72d8d61f3443414d320b22294c3356b4
Merge: c62aa49a7 f7ebc15c7
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Wed May 7 15:27:33 2025 +0200

    Merge branch 'master' into cmake-fix-compile

commit c62aa49a7323091df96c3505a6f764e541671b53
Merge: 859352589 b7ef8098f
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Tue Apr 15 16:02:25 2025 +0200

    Merge branch 'master' into cmake-fix-compile

commit 85935258985d01bfde953d80043b09d3cbf89e57
Merge: a6442c916 7ce4a4b9e
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Fri Feb 7 10:45:06 2025 +0100

    Merge branch 'master' into cmake-fix-compile

commit a6442c9169f344c9022b9ef5e537015cb632d82f
Merge: 39b8e7e95 2c74f13ea
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Wed Jan 8 16:12:35 2025 +0100

    Merge branch 'master' into cmake-fix-compile

commit 39b8e7e9513ba7fda880bcbb05f9a6a358e04bfe
Merge: b8a0eea4e b306cd771
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Fri Jan 3 10:27:33 2025 +0100

    Merge branch 'master' into cmake-fix-compile

commit b8a0eea4e6fa0a634086465dc92c805e14c31aae
Merge: cb972c740 cd09d91ec
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Fri Oct 11 11:26:30 2024 +0200

    Merge branch 'master' into cmake-fix-compile

commit cb972c74068dc0e8afbc03097bcd0d8831ad38d5
Merge: cf8907f14 1dd688191
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Mon Sep 23 15:40:19 2024 +0200

    Merge branch 'master' into cmake-fix-compile

commit cf8907f14c35c680eeef6eecc96942e4b029d00f
Merge: 3e9c99a12 032a6a79c
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Fri Sep 6 10:22:39 2024 +0200

    Merge branch 'master' into cmake-fix-compile

commit 3e9c99a12fbc3c48b8ca2fc461da528b2bc190e1
Merge: 6322d0e3f 7389fa73e
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Tue Aug 27 10:03:13 2024 +0200

    Merge branch 'master' into cmake-fix-compile

commit 6322d0e3f6bfe40d4103becf48c5c032c550d01c
Merge: aff997fef 7361cb2ee
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Tue Jul 30 16:55:49 2024 +0200

    Merge branch 'master' into cmake-fix-compile

commit aff997fef00951de2b9024c3d1211a6461fd0c4c
Merge: d29e30d40 8b6cae2a4
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Tue Jul 16 18:27:41 2024 +0200

    Merge branch 'master' into cmake-fix-compile

commit d29e30d403472d4e254169046fd80a5cf27c8d5e
Merge: e83b361bb 212a319f4
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Thu Jun 20 09:42:22 2024 +0200

    Merge branch 'master' into cmake-fix-compile

commit e83b361bbdc6dc061823dd5ff0d68d51798bb541
Merge: d7a524c41 6d53bfd28
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Wed Jun 12 09:41:47 2024 +0200

    Merge branch 'master' into cmake-fix-compile

commit d7a524c410ae999502d39dfb4e087f0d10112417
Merge: b19fff9f0 32f78a42c
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Fri May 24 18:24:26 2024 +0200

    Merge branch 'master' into cmake-fix-compile

commit b19fff9f0d6bdedc7e318c5629d366e7b0d6c5f2
Merge: 82896c86a 33eca66f8
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Tue May 21 10:45:38 2024 +0200

    Merge branch 'master' into cmake-fix-compile

commit 82896c86a83c2ff42c1f1aef42d31a4b3a71a12a
Merge: 276d19527 eccd8f143
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Mon May 20 18:30:52 2024 +0200

    Merge branch 'master' into cmake-fix-compile

commit 276d195273e0d0047e42a31fddf994bb2f979325
Merge: c22c2e344 6d94c6b6f
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Tue May 14 10:28:17 2024 +0200

    Merge branch 'master' into cmake-fix-compile

commit c22c2e344c7b04fbb1417ef6c4de9d70a8f827dc
Merge: d5ab68537 1ba439b2f
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Mon May 6 12:45:35 2024 +0200

    Merge branch 'master' into cmake-fix-compile

commit d5ab685375a608c8dfcb755225bed23ad72a4f32
Author: Massimo Petracca <mazuma88@hotmail.com>
Date:   Tue Apr 23 16:01:06 2024 +0200

    fix parallel targets